### PR TITLE
Local app store

### PR DESCRIPTION
**Pull request by Toshbrown**
Hi @yousefamar 

Can you give me a hand with this?

There are a couple of things that need changing for running locally in dev mode: 

I'm setting an env var LOCAL_MODE=1 if this is present:

Can you disable the login and remove the need to re-captcha?

Also, would it be easy to move to nedb rather than mongo so save starting another container. 

I had a look at implementing this but was foiled by ls once again ;-(

### CODE REVIEW

**Comment by yousefamar** [comment]
Ah, of course, I'll port to JS while I'm at it. I'll do this before the day is up. Should I push directly to upstream localAppStore branch?

There are also a whole bunch of things we could change about how the remote one works too eventually. I added all that stuff way back when going in blind based on how I imagined it might work, rather than how it should.

**Comment by Toshbrown** [comment]
Cool thanks, 

Just push to this branch Then we can merge it once we are happy.

**Comment by yousefamar** [comment]
The `autoload` option in nedb really helps with modularisation and simplified the code a bunch. Mongo forced async, and module exports had to be sync, hence my original hacks, so that's another plus.

BTW, on localhost, I believe any random reCAPTCHA key works for development anyway, but I agree that it's cleaner to remove login as a whole. I'll make it so that in LOCAL_MODE, you treat all requests as being part of some special admin-type account session.

**Comment by yousefamar** [comment]
`LOCAL_MODE` now brings you straight to dashboard and any manifests you upload are uploaded as a fake user called "localuser" with an `_id` of -1. Switched to nedb, and for the most part, it seems that the methods are the same as for mongo, but I did notice a few differences (natural order sort, find all needs empty object). If you spot any mongo-ism like that please do quash.

I forgot how much code I wrote for this, so porting to JS is not as super straightforward as I thought it would be. :P I'll take it module by module as we edit stuff, and any new modules we can require as JS. Likely a lot subject to rewriting too.

**Comment by Toshbrown** [comment]
Looks good, I will give it a quick try and merge it in

**Pull request merged**
